// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.19.6
// source: zchat/v1/zchat.proto

package zchatv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageStatus int32

const (
	MessageStatus_MESSAGE_STATUS_UNSPECIFIED MessageStatus = 0
	MessageStatus_MESSAGE_STATUS_PENDING     MessageStatus = 1
	MessageStatus_MESSAGE_STATUS_SENT        MessageStatus = 2
	MessageStatus_MESSAGE_STATUS_DELIVERED   MessageStatus = 3
	MessageStatus_MESSAGE_STATUS_READ        MessageStatus = 4
	MessageStatus_MESSAGE_STATUS_FAILED      MessageStatus = 5
)

// Enum value maps for MessageStatus.
var (
	MessageStatus_name = map[int32]string{
		0: "MESSAGE_STATUS_UNSPECIFIED",
		1: "MESSAGE_STATUS_PENDING",
		2: "MESSAGE_STATUS_SENT",
		3: "MESSAGE_STATUS_DELIVERED",
		4: "MESSAGE_STATUS_READ",
		5: "MESSAGE_STATUS_FAILED",
	}
	MessageStatus_value = map[string]int32{
		"MESSAGE_STATUS_UNSPECIFIED": 0,
		"MESSAGE_STATUS_PENDING":     1,
		"MESSAGE_STATUS_SENT":        2,
		"MESSAGE_STATUS_DELIVERED":   3,
		"MESSAGE_STATUS_READ":        4,
		"MESSAGE_STATUS_FAILED":      5,
	}
)

func (x MessageStatus) Enum() *MessageStatus {
	p := new(MessageStatus)
	*p = x
	return p
}

func (x MessageStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_zchat_v1_zchat_proto_enumTypes[0].Descriptor()
}

func (MessageStatus) Type() protoreflect.EnumType {
	return &file_zchat_v1_zchat_proto_enumTypes[0]
}

func (x MessageStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageStatus.Descriptor instead.
func (MessageStatus) EnumDescriptor() ([]byte, []int) {
	return file_zchat_v1_zchat_proto_rawDescGZIP(), []int{0}
}

type ConnectionStatus int32

const (
	ConnectionStatus_CONNECTION_STATUS_UNSPECIFIED  ConnectionStatus = 0
	ConnectionStatus_CONNECTION_STATUS_DISCONNECTED ConnectionStatus = 1
	ConnectionStatus_CONNECTION_STATUS_CONNECTING   ConnectionStatus = 2
	ConnectionStatus_CONNECTION_STATUS_CONNECTED    ConnectionStatus = 3
	ConnectionStatus_CONNECTION_STATUS_LOGGED_OUT   ConnectionStatus = 4 // needs QR pairing
)

// Enum value maps for ConnectionStatus.
var (
	ConnectionStatus_name = map[int32]string{
		0: "CONNECTION_STATUS_UNSPECIFIED",
		1: "CONNECTION_STATUS_DISCONNECTED",
		2: "CONNECTION_STATUS_CONNECTING",
		3: "CONNECTION_STATUS_CONNECTED",
		4: "CONNECTION_STATUS_LOGGED_OUT",
	}
	ConnectionStatus_value = map[string]int32{
		"CONNECTION_STATUS_UNSPECIFIED":  0,
		"CONNECTION_STATUS_DISCONNECTED": 1,
		"CONNECTION_STATUS_CONNECTING":   2,
		"CONNECTION_STATUS_CONNECTED":    3,
		"CONNECTION_STATUS_LOGGED_OUT":   4,
	}
)

func (x ConnectionStatus) Enum() *ConnectionStatus {
	p := new(ConnectionStatus)
	*p = x
	return p
}

func (x ConnectionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConnectionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_zchat_v1_zchat_proto_enumTypes[1].Descriptor()
}

func (ConnectionStatus) Type() protoreflect.EnumType {
	return &file_zchat_v1_zchat_proto_enumTypes[1]
}

func (x ConnectionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConnectionStatus.Descriptor instead.
func (ConnectionStatus) EnumDescriptor() ([]byte, []int) {
	return file_zchat_v1_zchat_proto_rawDescGZIP(), []int{1}
}

type Chat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jid           string                 `protobuf:"bytes,1,opt,name=jid,proto3" json:"jid,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Unread        int32                  `protobuf:"varint,3,opt,name=unread,proto3" json:"unread,omitempty"`
	Archived      bool                   `protobuf:"varint,4,opt,name=archived,proto3" json:"archived,omitempty"`
	Pinned        bool                   `protobuf:"varint,5,opt,name=pinned,proto3" json:"pinned,omitempty"`
	LastMessage   string                 `protobuf:"bytes,6,opt,name=last_message,json=lastMessage,proto3" json:"last_message,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"` // unix seconds
	IsGroup       bool                   `protobuf:"varint,8,opt,name=is_group,json=isGroup,proto3" json:"is_group,omitempty"`
	MutedUntil    int64                  `protobuf:"varint,9,opt,name=muted_until,json=mutedUntil,proto3" json:"muted_until,omitempty"` // unix seconds; -1 = muted forever, 0 = not muted
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chat) Reset() {
	*x = Chat{}
	mi := &file_zchat_v1_zchat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chat) ProtoMessage() {}

func (x *Chat) ProtoReflect() protoreflect.Message {
	mi := &file_zchat_v1_zchat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chat.ProtoReflect.Descriptor instead.
func (*Chat) Descriptor() ([]byte, []int) {
	return file_zchat_v1_zchat_proto_rawDescGZIP(), []int{0}
}

func (x *Chat) GetJid() string {
	if x != nil {
		return x.Jid
	}
	return ""
}

func (x *Chat) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Chat) GetUnread() int32 {
	if x != nil {
		return x.Unread
	}
	return 0
}

func (x *Chat) GetArchived() bool {
	if x != nil {
		return x.Archived
	}
	return false
}

func (x *Chat) GetPinned() bool {
	if x != nil {
		return x.Pinned
	}
	return false
}

func (x *Chat) GetLastMessage() string {
	if x != nil {
		return x.LastMessage
	}
	return ""
}

func (x *Chat) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *Chat) GetIsGroup() bool {
	if x != nil {
		return x.IsGroup
	}
	return false
}

func (x *Chat) GetMutedUntil() int64 {
	if x != nil {
		return x.MutedUntil
	}
	return 0
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ChatJid       string                 `protobuf:"bytes,2,opt,name=chat_jid,json=chatJid,proto3" json:"chat_jid,omitempty"`
	Sender        string                 `protobuf:"bytes,3,opt,name=sender,proto3" json:"sender,omitempty"`
	SenderName    string                 `protobuf:"bytes,4,opt,name=sender_name,json=senderName,proto3" json:"sender_name,omitempty"`
	Body          string                 `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	Type          string                 `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`            // "text", "image", "video", "audio", "document", "sticker"
	Timestamp     int64                  `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // unix seconds
	Outgoing      bool                   `protobuf:"varint,8,opt,name=outgoing,proto3" json:"outgoing,omitempty"`
	Status        MessageStatus          `protobuf:"varint,9,opt,name=status,proto3,enum=zchat.v1.MessageStatus" json:"status,omitempty"`
	Media         *MediaInfo             `protobuf:"bytes,10,opt,name=media,proto3" json:"media,omitempty"`   // set when type != "text"
	Quoted        *QuotedMessage         `protobuf:"bytes,11,opt,name=quoted,proto3" json:"quoted,omitempty"` // set when this message replies to another
	Forwarded     bool                   `protobuf:"varint,12,opt,name=forwarded,proto3" json:"forwarded,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_zchat_v1_zchat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_zchat_v1_zchat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_zchat_v1_zchat_proto_rawDescGZIP(), []int{1}
}

func (x *Message) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Message) GetChatJid() string {
	if x != nil {
		return x.ChatJid
	}
	return ""
}

func (x *Message) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *Message) GetSenderName() string {
	if x != nil {
		return x.SenderName
	}
	return ""
}

func (x *Message) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Message) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Message) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Message) GetOutgoing() bool {
	if x != nil {
		return x.Outgoing
	}
	return false
}

func (x *Message) GetStatus() MessageStatus {
	if x != nil {
		return x.Status
	}
	return MessageStatus_MESSAGE_STATUS_UNSPECIFIED
}

func (x *Message) GetMedia() *MediaInfo {
	if x != nil {
		return x.Media
	}
	return nil
}

func (x *Message) GetQuoted() *QuotedMessage {
	if x != nil {
		return x.Quoted
	}
	return nil
}

func (x *Message) GetForwarded() bool {
	if x != nil {
		return x.Forwarded
	}
	return false
}

// QuotedMessage is the snapshot of the message a reply points at. The original
// may be missing locally, so the preview text is stored alongside the id.
type QuotedMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Sender        string                 `protobuf:"bytes,2,opt,name=sender,proto3" json:"sender,omitempty"`
	SenderName    string                 `protobuf:"bytes,3,opt,name=sender_name,json=senderName,proto3" json:"sender_name,omitempty"`
	Body          string                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	Type          string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuotedMessage) Reset() {
	*x = QuotedMessage{}
	mi := &file_zchat_v1_zchat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuotedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuotedMessage) ProtoMessage() {}

func (x *QuotedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_zchat_v1_zchat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuotedMessage.ProtoReflect.Descriptor instead.
func (*QuotedMessage) Descriptor() ([]byte, []int) {
	return file_zchat_v1_zchat_proto_rawDescGZIP(), []int{2}
}

func (x *QuotedMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *QuotedMessage) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *QuotedMessage) GetSenderName() string {
	if x != nil {
		return x.SenderName
	}
	return ""
}

func (x *QuotedMessage) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *QuotedMessage) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

// MediaInfo describes an attachment. path is empty until the media has been
// downloaded; clients call DownloadMedia to materialise it.
type MediaInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mime          string                 `protobuf:"bytes,1,opt,name=mime,proto3" json:"mime,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Filename      string                 `protobuf:"bytes,3,opt,name=filename,proto3" json:"filename,omitempty"`
	Caption       string                 `protobuf:"bytes,4,opt,name=caption,proto3" json:"caption,omitempty"`
	Path          string                 `protobuf:"bytes,5,opt,name=path,proto3" json:"path,omitempty"`           // local file path, empty when not downloaded yet
	Thumbnail     []byte                 `protobuf:"bytes,6,opt,name=thumbnail,proto3" json:"thumbnail,omitempty"` // JPEG preview embedded by WhatsApp, may be empty
	Width         int32                  `protobuf:"varint,7,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,8,opt,name=height,proto3" json:"height,omitempty"`
	Duration      int32                  `protobuf:"varint,9,opt,name=duration,proto3" json:"duration,omitempty"` // seconds, audio and video only
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaInfo) Reset() {
	*x = MediaInfo{}
	mi := &file_zchat_v1_zchat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaInfo) ProtoMessage() {}

func (x *MediaInfo) ProtoReflect() protoreflect.Message {
	mi := &file_zchat_v1_zchat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaInfo.ProtoReflect.Descriptor instead.
func (*MediaInfo) Descriptor() ([]byte, []int) {
	return file_zchat_v1_zchat_proto_rawDescGZIP(), []int{3}
}

func (x *MediaInfo) GetMime() string {
	if x != nil {
		return x.Mime
	}
	return ""
}

func (x *MediaInfo) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *MediaInfo) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *MediaInfo) GetCaption() string {
	if x != nil {
		return x.Caption
	}
	return ""
}

func (x *MediaInfo) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *MediaInfo) GetThumbnail() []byte {
	if x != nil {
		return x.Thumbnail
	}
	return nil
}

func (x *MediaInfo) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *MediaInfo) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *MediaInfo) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

type ConnectionState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        ConnectionStatus       `protobuf:"varint,1,opt,name=status,proto3,enum=zchat.v1.ConnectionStatus" json:"status,omitempty"`
	OwnJid        string                 `protobuf:"bytes,2,opt,name=own_jid,json=ownJid,proto3" json:"own_jid,omitempty"`
	PushName      string                 `protobuf:"bytes,3,opt,name=push_name,json=pushName,proto3" json:"push_name,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectionState) Reset() {
	*x = ConnectionState{}
	mi := &file_zchat_v1_zchat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionState) ProtoMessage() {}

func (x *ConnectionState) ProtoReflect() protoreflect.Message {
	mi := &file_zchat_v1_zchat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionState.ProtoReflect.Descriptor instead.
func (*ConnectionState) Descriptor() ([]byte, []int) {
	return file_zchat_v1_zchat_proto_rawDescGZIP(), []int{4}
}

func (x *ConnectionState) GetStatus() ConnectionStatus {
	if x != nil {
		return x.Status
	}
	return ConnectionStatus_CONNECTION_STATUS_UNSPECIFIED
}

func (x *ConnectionState) GetOwnJid() string {
	if x != nil {
		return x.OwnJid
	}
	return ""
}

func (x *ConnectionState) GetPushName() string {
	if x != nil {
		return x.PushName
	}
	return ""
}

func (x *ConnectionState) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetChatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Archived      bool                   `protobuf:"varint,3,opt,name=archived,proto3" json:"archived,omitempty"` // return the archived list instead of the active one
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChatsRequest) Reset() {
	*x = GetChatsRequest{}
	mi := &file_zchat_v1_zchat_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatsRequest) ProtoMessage() {}

func (x *GetChatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zchat_v1_zchat_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatsRequest.ProtoReflect.Descriptor instead.
func (*GetChatsRequest) Descriptor() ([]byte, []int) {
	return file_zchat_v1_zchat_proto_rawDescGZIP(), []int{5}
}

func (x *GetChatsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetChatsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetChatsRequest) GetArchived() bool {
	if x != nil {
		return x.Archived
	}
	return false
}

type GetChatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chats         []*Chat                `protobuf:"bytes,1,rep,name=chats,proto3" json:"chats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChatsResponse) Reset() {
	*x = GetChatsResponse{}
	mi := &file_zchat_v1_zchat_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatsResponse) ProtoMessage() {}

func (x *GetChatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zchat_v1_zchat_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatsResponse.ProtoReflect.Descriptor instead.
func (*GetChatsResponse) Descriptor() ([]byte, []int) {
	return file_zchat_v1_zchat_proto_rawDescGZIP(), []int{6}
}

func (x *GetChatsResponse) GetChats() []*Chat {
	if x != nil {
		return x.Chats
	}
	return nil
}

type GetMessagesRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ChatJid         string                 `protobuf:"bytes,1,opt,name=chat_jid,json=chatJid,proto3" json:"chat_jid,omitempty"`
	Limit           int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`                                            // daemon clamps to 200 when 0 or >200
	BeforeTimestamp int64                  `protobuf:"varint,3,opt,name=before_timestamp,json=beforeTimestamp,proto3" json:"before_timestamp,omitempty"` // 0 = most recent
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetMessagesRequest) Reset() {
	*x = GetMessagesRequest{}
	mi := &file_zchat_v1_zchat_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessagesRequest) ProtoMessage() {}

func (x *GetMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zchat_v1_zchat_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessagesRequest.ProtoReflect.Descriptor instead.
func (*GetMessagesRequest) Descriptor() ([]byte, []int) {
	return file_zchat_v1_zchat_proto_rawDescGZIP(), []int{7}
}

func (x *GetMessagesRequest) GetChatJid() string {
	if x != nil {
		return x.ChatJid
	}
	return ""
}

func (x *GetMessagesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetMessagesRequest) GetBeforeTimestamp() int64 {
	if x != nil {
		return x.BeforeTimestamp
	}
	return 0
}

type GetMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*Message             `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessagesResponse) Reset() {
	*x = GetMessagesResponse{}
	mi := &file_zchat_v1_zchat_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessagesResponse) ProtoMessage() {}

func (x *GetMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zchat_v1_zchat_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessagesResponse.ProtoReflect.Descriptor instead.
func (*GetMessagesResponse) Descriptor() ([]byte, []int) {
	return file_zchat_v1_zchat_proto_rawDescGZIP(), []int{8}
}

func (x *GetMessagesResponse) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

type SendMessageRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ChatJid         string                 `protobuf:"bytes,1,opt,name=chat_jid,json=chatJid,proto3" json:"chat_jid,omitempty"`
	Body            string                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	QuotedMessageId string                 `protobuf:"bytes,3,opt,name=quoted_message_id,json=quotedMessageId,proto3" json:"quoted_message_id,omitempty"` // optional; reply to this message
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_zchat_v1_zchat_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zchat_v1_zchat_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_zchat_v1_zchat_proto_rawDescGZIP(), []int{9}
}

func (x *SendMessageRequest) GetChatJid() string {
	if x != nil {
		return x.ChatJid
	}
	return ""
}

func (x *SendMessageRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *SendMessageRequest) GetQuotedMessageId() string {
	if x != nil {
		return x.QuotedMessageId
	}
	return ""
}

type SendMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *Message               `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageResponse) Reset() {
	*x = SendMessageResponse{}
	mi := &file_zchat_v1_zchat_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageResponse) ProtoMessage() {}

func (x *SendMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zchat_v1_zchat_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageResponse.ProtoReflect.Descriptor instead.
func (*SendMessageResponse) Descriptor() ([]byte, []int) {
	return file_zchat_v1_zchat_proto_rawDescGZIP(), []int{10}
}

func (x *SendMessageResponse) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

// SendMediaRequest uploads a local file as an attachment. The daemon reads
// file_path itself, so client and daemon must share a filesystem, which the
// Unix socket transport already implies.
type SendMediaRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ChatJid         string                 `protobuf:"bytes,1,opt,name=chat_jid,json=chatJid,proto3" json:"chat_jid,omitempty"`
	FilePath        string                 `protobuf:"bytes,2,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	Caption         string                 `protobuf:"bytes,3,opt,name=caption,proto3" json:"caption,omitempty"`
	QuotedMessageId string                 `protobuf:"bytes,4,opt,name=quoted_message_id,json=quotedMessageId,proto3" json:"quoted_message_id,omitempty"` // optional; reply to this message
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SendMediaRequest) Reset() {
	*x = SendMediaRequest{}
	mi := &file_zchat_v1_zchat_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMediaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMediaRequest) ProtoMessage() {}

func (x *SendMediaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zchat_v1_zchat_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMediaRequest.ProtoReflect.Descriptor instead.
func (*SendMediaRequest) Descriptor() ([]byte, []int) {
	return file_zchat_v1_zchat_proto_rawDescGZIP(), []int{11}
}

func (x *SendMediaRequest) GetChatJid() string {
	if x != nil {
		return x.ChatJid
	}
	return ""
}

func (x *SendMediaRequest) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *SendMediaRequest) GetCaption() string {
	if x != nil {
		return x.Caption
	}
	return ""
}

func (x *SendMediaRequest) GetQuotedMessageId() string {
	if x != nil {
		return x.QuotedMessageId
	}
	return ""
}

type SendMediaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *Message               `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMediaResponse) Reset() {
	*x = SendMediaResponse{}
	mi := &file_zchat_v1_zchat_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMediaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMediaResponse) ProtoMessage() {}

func (x *SendMediaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zchat_v1_zchat_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMediaResponse.ProtoReflect.Descriptor instead.
func (*SendMediaResponse) Descriptor() ([]byte, []int) {
	return file_zchat_v1_zchat_proto_rawDescGZIP(), []int{12}
}

func (x *SendMediaResponse) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

type ForwardMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	ToChatJid     string                 `protobuf:"bytes,2,opt,name=to_chat_jid,json=toChatJid,proto3" json:"to_chat_jid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardMessageRequest) Reset() {
	*x = ForwardMessageRequest{}
	mi := &file_zchat_v1_zchat_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardMessageRequest) ProtoMessage() {}

func (x *ForwardMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zchat_v1_zchat_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardMessageRequest.ProtoReflect.Descriptor instead.
func (*ForwardMessageRequest) Descriptor() ([]byte, []int) {
	return file_zchat_v1_zchat_proto_rawDescGZIP(), []int{13}
}

func (x *ForwardMessageRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *ForwardMessageRequest) GetToChatJid() string {
	if x != nil {
		return x.ToChatJid
	}
	return ""
}

type ForwardMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *Message               `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardMessageResponse) Reset() {
	*x = ForwardMessageResponse{}
	mi := &file_zchat_v1_zchat_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardMessageResponse) ProtoMessage() {}

func (x *ForwardMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zchat_v1_zchat_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardMessageResponse.ProtoReflect.Descriptor instead.
func (*ForwardMessageResponse) Descriptor() ([]byte, []int) {
	return file_zchat_v1_zchat_proto_rawDescGZIP(), []int{14}
}

func (x *ForwardMessageResponse) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

// DeleteMessageRequest removes a message locally. When revoke is set and the
// message is the user's own, it is also revoked for everyone.
type DeleteMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Revoke        bool                   `protobuf:"varint,2,opt,name=revoke,proto3" json:"revoke,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMessageRequest) Reset() {
	*x = DeleteMessageRequest{}
	mi := &file_zchat_v1_zchat_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMessageRequest) ProtoMessage() {}

func (x *DeleteMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zchat_v1_zchat_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMessageRequest.ProtoReflect.Descriptor instead.
func (*DeleteMessageRequest) Descriptor() ([]byte, []int) {
	return file_zchat_v1_zchat_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteMessageRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *DeleteMessageRequest) GetRevoke() bool {
	if x != nil {
		return x.Revoke
	}
	return false
}

type DeleteMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMessageResponse) Reset() {
	*x = DeleteMessageResponse{}
	mi := &file_zchat_v1_zchat_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMessageResponse) ProtoMessage() {}

func (x *DeleteMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zchat_v1_zchat_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMessageResponse.ProtoReflect.Descriptor instead.
func (*DeleteMessageResponse) Descriptor() ([]byte, []int) {
	return file_zchat_v1_zchat_proto_rawDescGZIP(), []int{16}
}

// UpdateChatRequest toggles local and app-state chat flags. Unset fields are
// left untouched.
type UpdateChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatJid       string                 `protobuf:"bytes,1,opt,name=chat_jid,json=chatJid,proto3" json:"chat_jid,omitempty"`
	Pinned        *bool                  `protobuf:"varint,2,opt,name=pinned,proto3,oneof" json:"pinned,omitempty"`
	Archived      *bool                  `protobuf:"varint,3,opt,name=archived,proto3,oneof" json:"archived,omitempty"`
	MutedUntil    *int64                 `protobuf:"varint,4,opt,name=muted_until,json=mutedUntil,proto3,oneof" json:"muted_until,omitempty"` // -1 = mute forever, 0 = unmute
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateChatRequest) Reset() {
	*x = UpdateChatRequest{}
	mi := &file_zchat_v1_zchat_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateChatRequest) ProtoMessage() {}

func (x *UpdateChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zchat_v1_zchat_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateChatRequest.ProtoReflect.Descriptor instead.
func (*UpdateChatRequest) Descriptor() ([]byte, []int) {
	return file_zchat_v1_zchat_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateChatRequest) GetChatJid() string {
	if x != nil {
		return x.ChatJid
	}
	return ""
}

func (x *UpdateChatRequest) GetPinned() bool {
	if x != nil && x.Pinned != nil {
		return *x.Pinned
	}
	return false
}

func (x *UpdateChatRequest) GetArchived() bool {
	if x != nil && x.Archived != nil {
		return *x.Archived
	}
	return false
}

func (x *UpdateChatRequest) GetMutedUntil() int64 {
	if x != nil && x.MutedUntil != nil {
		return *x.MutedUntil
	}
	return 0
}

type UpdateChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chat          *Chat                  `protobuf:"bytes,1,opt,name=chat,proto3" json:"chat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateChatResponse) Reset() {
	*x = UpdateChatResponse{}
	mi := &file_zchat_v1_zchat_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateChatResponse) ProtoMessage() {}

func (x *UpdateChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zchat_v1_zchat_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateChatResponse.ProtoReflect.Descriptor instead.
func (*UpdateChatResponse) Descriptor() ([]byte, []int) {
	return file_zchat_v1_zchat_proto_rawDescGZIP(), []int{18}
}

func (x *UpdateChatResponse) GetChat() *Chat {
	if x != nil {
		return x.Chat
	}
	return nil
}

type GetConnectionStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConnectionStateRequest) Reset() {
	*x = GetConnectionStateRequest{}
	mi := &file_zchat_v1_zchat_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConnectionStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConnectionStateRequest) ProtoMessage() {}

func (x *GetConnectionStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zchat_v1_zchat_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConnectionStateRequest.ProtoReflect.Descriptor instead.
func (*GetConnectionStateRequest) Descriptor() ([]byte, []int) {
	return file_zchat_v1_zchat_proto_rawDescGZIP(), []int{19}
}

type LogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_zchat_v1_zchat_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zchat_v1_zchat_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_zchat_v1_zchat_proto_rawDescGZIP(), []int{20}
}

type LogoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutResponse) Reset() {
	*x = LogoutResponse{}
	mi := &file_zchat_v1_zchat_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutResponse) ProtoMessage() {}

func (x *LogoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zchat_v1_zchat_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutResponse.ProtoReflect.Descriptor instead.
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return file_zchat_v1_zchat_proto_rawDescGZIP(), []int{21}
}

type DownloadMediaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadMediaRequest) Reset() {
	*x = DownloadMediaRequest{}
	mi := &file_zchat_v1_zchat_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadMediaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadMediaRequest) ProtoMessage() {}

func (x *DownloadMediaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zchat_v1_zchat_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadMediaRequest.ProtoReflect.Descriptor instead.
func (*DownloadMediaRequest) Descriptor() ([]byte, []int) {
	return file_zchat_v1_zchat_proto_rawDescGZIP(), []int{22}
}

func (x *DownloadMediaRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

type DownloadMediaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *Message               `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadMediaResponse) Reset() {
	*x = DownloadMediaResponse{}
	mi := &file_zchat_v1_zchat_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadMediaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadMediaResponse) ProtoMessage() {}

func (x *DownloadMediaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zchat_v1_zchat_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadMediaResponse.ProtoReflect.Descriptor instead.
func (*DownloadMediaResponse) Descriptor() ([]byte, []int) {
	return file_zchat_v1_zchat_proto_rawDescGZIP(), []int{23}
}

func (x *DownloadMediaResponse) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

type SearchChatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchChatsRequest) Reset() {
	*x = SearchChatsRequest{}
	mi := &file_zchat_v1_zchat_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchChatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchChatsRequest) ProtoMessage() {}

func (x *SearchChatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zchat_v1_zchat_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchChatsRequest.ProtoReflect.Descriptor instead.
func (*SearchChatsRequest) Descriptor() ([]byte, []int) {
	return file_zchat_v1_zchat_proto_rawDescGZIP(), []int{24}
}

func (x *SearchChatsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchChatsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type SearchChatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chats         []*Chat                `protobuf:"bytes,1,rep,name=chats,proto3" json:"chats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchChatsResponse) Reset() {
	*x = SearchChatsResponse{}
	mi := &file_zchat_v1_zchat_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchChatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchChatsResponse) ProtoMessage() {}

func (x *SearchChatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zchat_v1_zchat_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchChatsResponse.ProtoReflect.Descriptor instead.
func (*SearchChatsResponse) Descriptor() ([]byte, []int) {
	return file_zchat_v1_zchat_proto_rawDescGZIP(), []int{25}
}

func (x *SearchChatsResponse) GetChats() []*Chat {
	if x != nil {
		return x.Chats
	}
	return nil
}

type StreamEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamEventsRequest) Reset() {
	*x = StreamEventsRequest{}
	mi := &file_zchat_v1_zchat_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamEventsRequest) ProtoMessage() {}

func (x *StreamEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zchat_v1_zchat_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamEventsRequest.ProtoReflect.Descriptor instead.
func (*StreamEventsRequest) Descriptor() ([]byte, []int) {
	return file_zchat_v1_zchat_proto_rawDescGZIP(), []int{26}
}

type QRUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QRUpdate) Reset() {
	*x = QRUpdate{}
	mi := &file_zchat_v1_zchat_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QRUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QRUpdate) ProtoMessage() {}

func (x *QRUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_zchat_v1_zchat_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QRUpdate.ProtoReflect.Descriptor instead.
func (*QRUpdate) Descriptor() ([]byte, []int) {
	return file_zchat_v1_zchat_proto_rawDescGZIP(), []int{27}
}

func (x *QRUpdate) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *QRUpdate) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

type MessageDeleted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ChatJid       string                 `protobuf:"bytes,2,opt,name=chat_jid,json=chatJid,proto3" json:"chat_jid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageDeleted) Reset() {
	*x = MessageDeleted{}
	mi := &file_zchat_v1_zchat_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageDeleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageDeleted) ProtoMessage() {}

func (x *MessageDeleted) ProtoReflect() protoreflect.Message {
	mi := &file_zchat_v1_zchat_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageDeleted.ProtoReflect.Descriptor instead.
func (*MessageDeleted) Descriptor() ([]byte, []int) {
	return file_zchat_v1_zchat_proto_rawDescGZIP(), []int{28}
}

func (x *MessageDeleted) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MessageDeleted) GetChatJid() string {
	if x != nil {
		return x.ChatJid
	}
	return ""
}

type Event struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Event_MessageReceived
	//	*Event_MessageUpdated
	//	*Event_ChatUpdated
	//	*Event_QrUpdated
	//	*Event_ConnectionState
	//	*Event_MessageDeleted
	Payload       isEvent_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_zchat_v1_zchat_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_zchat_v1_zchat_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_zchat_v1_zchat_proto_rawDescGZIP(), []int{29}
}

func (x *Event) GetPayload() isEvent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Event) GetMessageReceived() *Message {
	if x != nil {
		if x, ok := x.Payload.(*Event_MessageReceived); ok {
			return x.MessageReceived
		}
	}
	return nil
}

func (x *Event) GetMessageUpdated() *Message {
	if x != nil {
		if x, ok := x.Payload.(*Event_MessageUpdated); ok {
			return x.MessageUpdated
		}
	}
	return nil
}

func (x *Event) GetChatUpdated() *Chat {
	if x != nil {
		if x, ok := x.Payload.(*Event_ChatUpdated); ok {
			return x.ChatUpdated
		}
	}
	return nil
}

func (x *Event) GetQrUpdated() *QRUpdate {
	if x != nil {
		if x, ok := x.Payload.(*Event_QrUpdated); ok {
			return x.QrUpdated
		}
	}
	return nil
}

func (x *Event) GetConnectionState() *ConnectionState {
	if x != nil {
		if x, ok := x.Payload.(*Event_ConnectionState); ok {
			return x.ConnectionState
		}
	}
	return nil
}

func (x *Event) GetMessageDeleted() *MessageDeleted {
	if x != nil {
		if x, ok := x.Payload.(*Event_MessageDeleted); ok {
			return x.MessageDeleted
		}
	}
	return nil
}

type isEvent_Payload interface {
	isEvent_Payload()
}

type Event_MessageReceived struct {
	MessageReceived *Message `protobuf:"bytes,1,opt,name=message_received,json=messageReceived,proto3,oneof"`
}

type Event_MessageUpdated struct {
	MessageUpdated *Message `protobuf:"bytes,2,opt,name=message_updated,json=messageUpdated,proto3,oneof"`
}

type Event_ChatUpdated struct {
	ChatUpdated *Chat `protobuf:"bytes,3,opt,name=chat_updated,json=chatUpdated,proto3,oneof"`
}

type Event_QrUpdated struct {
	QrUpdated *QRUpdate `protobuf:"bytes,4,opt,name=qr_updated,json=qrUpdated,proto3,oneof"`
}

type Event_ConnectionState struct {
	ConnectionState *ConnectionState `protobuf:"bytes,5,opt,name=connection_state,json=connectionState,proto3,oneof"`
}

type Event_MessageDeleted struct {
	MessageDeleted *MessageDeleted `protobuf:"bytes,6,opt,name=message_deleted,json=messageDeleted,proto3,oneof"`
}

func (*Event_MessageReceived) isEvent_Payload() {}

func (*Event_MessageUpdated) isEvent_Payload() {}

func (*Event_ChatUpdated) isEvent_Payload() {}

func (*Event_QrUpdated) isEvent_Payload() {}

func (*Event_ConnectionState) isEvent_Payload() {}

func (*Event_MessageDeleted) isEvent_Payload() {}

var File_zchat_v1_zchat_proto protoreflect.FileDescriptor

const file_zchat_v1_zchat_proto_rawDesc = "" +
	"\n" +
	"\x14zchat/v1/zchat.proto\x12\bzchat.v1\"\xf6\x01\n" +
	"\x04Chat\x12\x10\n" +
	"\x03jid\x18\x01 \x01(\tR\x03jid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06unread\x18\x03 \x01(\x05R\x06unread\x12\x1a\n" +
	"\barchived\x18\x04 \x01(\bR\barchived\x12\x16\n" +
	"\x06pinned\x18\x05 \x01(\bR\x06pinned\x12!\n" +
	"\flast_message\x18\x06 \x01(\tR\vlastMessage\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\x03R\tupdatedAt\x12\x19\n" +
	"\bis_group\x18\b \x01(\bR\aisGroup\x12\x1f\n" +
	"\vmuted_until\x18\t \x01(\x03R\n" +
	"mutedUntil\"\xfa\x02\n" +
	"\aMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bchat_jid\x18\x02 \x01(\tR\achatJid\x12\x16\n" +
	"\x06sender\x18\x03 \x01(\tR\x06sender\x12\x1f\n" +
	"\vsender_name\x18\x04 \x01(\tR\n" +
	"senderName\x12\x12\n" +
	"\x04body\x18\x05 \x01(\tR\x04body\x12\x12\n" +
	"\x04type\x18\x06 \x01(\tR\x04type\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\x03R\ttimestamp\x12\x1a\n" +
	"\boutgoing\x18\b \x01(\bR\boutgoing\x12/\n" +
	"\x06status\x18\t \x01(\x0e2\x17.zchat.v1.MessageStatusR\x06status\x12)\n" +
	"\x05media\x18\n" +
	" \x01(\v2\x13.zchat.v1.MediaInfoR\x05media\x12/\n" +
	"\x06quoted\x18\v \x01(\v2\x17.zchat.v1.QuotedMessageR\x06quoted\x12\x1c\n" +
	"\tforwarded\x18\f \x01(\bR\tforwarded\"\x80\x01\n" +
	"\rQuotedMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06sender\x18\x02 \x01(\tR\x06sender\x12\x1f\n" +
	"\vsender_name\x18\x03 \x01(\tR\n" +
	"senderName\x12\x12\n" +
	"\x04body\x18\x04 \x01(\tR\x04body\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\"\xe5\x01\n" +
	"\tMediaInfo\x12\x12\n" +
	"\x04mime\x18\x01 \x01(\tR\x04mime\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12\x1a\n" +
	"\bfilename\x18\x03 \x01(\tR\bfilename\x12\x18\n" +
	"\acaption\x18\x04 \x01(\tR\acaption\x12\x12\n" +
	"\x04path\x18\x05 \x01(\tR\x04path\x12\x1c\n" +
	"\tthumbnail\x18\x06 \x01(\fR\tthumbnail\x12\x14\n" +
	"\x05width\x18\a \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\b \x01(\x05R\x06height\x12\x1a\n" +
	"\bduration\x18\t \x01(\x05R\bduration\"\x91\x01\n" +
	"\x0fConnectionState\x122\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1a.zchat.v1.ConnectionStatusR\x06status\x12\x17\n" +
	"\aown_jid\x18\x02 \x01(\tR\x06ownJid\x12\x1b\n" +
	"\tpush_name\x18\x03 \x01(\tR\bpushName\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"[\n" +
	"\x0fGetChatsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\x12\x1a\n" +
	"\barchived\x18\x03 \x01(\bR\barchived\"8\n" +
	"\x10GetChatsResponse\x12$\n" +
	"\x05chats\x18\x01 \x03(\v2\x0e.zchat.v1.ChatR\x05chats\"p\n" +
	"\x12GetMessagesRequest\x12\x19\n" +
	"\bchat_jid\x18\x01 \x01(\tR\achatJid\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12)\n" +
	"\x10before_timestamp\x18\x03 \x01(\x03R\x0fbeforeTimestamp\"D\n" +
	"\x13GetMessagesResponse\x12-\n" +
	"\bmessages\x18\x01 \x03(\v2\x11.zchat.v1.MessageR\bmessages\"o\n" +
	"\x12SendMessageRequest\x12\x19\n" +
	"\bchat_jid\x18\x01 \x01(\tR\achatJid\x12\x12\n" +
	"\x04body\x18\x02 \x01(\tR\x04body\x12*\n" +
	"\x11quoted_message_id\x18\x03 \x01(\tR\x0fquotedMessageId\"B\n" +
	"\x13SendMessageResponse\x12+\n" +
	"\amessage\x18\x01 \x01(\v2\x11.zchat.v1.MessageR\amessage\"\x90\x01\n" +
	"\x10SendMediaRequest\x12\x19\n" +
	"\bchat_jid\x18\x01 \x01(\tR\achatJid\x12\x1b\n" +
	"\tfile_path\x18\x02 \x01(\tR\bfilePath\x12\x18\n" +
	"\acaption\x18\x03 \x01(\tR\acaption\x12*\n" +
	"\x11quoted_message_id\x18\x04 \x01(\tR\x0fquotedMessageId\"@\n" +
	"\x11SendMediaResponse\x12+\n" +
	"\amessage\x18\x01 \x01(\v2\x11.zchat.v1.MessageR\amessage\"V\n" +
	"\x15ForwardMessageRequest\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x1e\n" +
	"\vto_chat_jid\x18\x02 \x01(\tR\ttoChatJid\"E\n" +
	"\x16ForwardMessageResponse\x12+\n" +
	"\amessage\x18\x01 \x01(\v2\x11.zchat.v1.MessageR\amessage\"M\n" +
	"\x14DeleteMessageRequest\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x16\n" +
	"\x06revoke\x18\x02 \x01(\bR\x06revoke\"\x17\n" +
	"\x15DeleteMessageResponse\"\xba\x01\n" +
	"\x11UpdateChatRequest\x12\x19\n" +
	"\bchat_jid\x18\x01 \x01(\tR\achatJid\x12\x1b\n" +
	"\x06pinned\x18\x02 \x01(\bH\x00R\x06pinned\x88\x01\x01\x12\x1f\n" +
	"\barchived\x18\x03 \x01(\bH\x01R\barchived\x88\x01\x01\x12$\n" +
	"\vmuted_until\x18\x04 \x01(\x03H\x02R\n" +
	"mutedUntil\x88\x01\x01B\t\n" +
	"\a_pinnedB\v\n" +
	"\t_archivedB\x0e\n" +
	"\f_muted_until\"8\n" +
	"\x12UpdateChatResponse\x12\"\n" +
	"\x04chat\x18\x01 \x01(\v2\x0e.zchat.v1.ChatR\x04chat\"\x1b\n" +
	"\x19GetConnectionStateRequest\"\x0f\n" +
	"\rLogoutRequest\"\x10\n" +
	"\x0eLogoutResponse\"5\n" +
	"\x14DownloadMediaRequest\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\"D\n" +
	"\x15DownloadMediaResponse\x12+\n" +
	"\amessage\x18\x01 \x01(\v2\x11.zchat.v1.MessageR\amessage\"@\n" +
	"\x12SearchChatsRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\";\n" +
	"\x13SearchChatsResponse\x12$\n" +
	"\x05chats\x18\x01 \x03(\v2\x0e.zchat.v1.ChatR\x05chats\"\x15\n" +
	"\x13StreamEventsRequest\"=\n" +
	"\bQRUpdate\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\x03R\texpiresAt\";\n" +
	"\x0eMessageDeleted\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bchat_jid\x18\x02 \x01(\tR\achatJid\"\x87\x03\n" +
	"\x05Event\x12>\n" +
	"\x10message_received\x18\x01 \x01(\v2\x11.zchat.v1.MessageH\x00R\x0fmessageReceived\x12<\n" +
	"\x0fmessage_updated\x18\x02 \x01(\v2\x11.zchat.v1.MessageH\x00R\x0emessageUpdated\x123\n" +
	"\fchat_updated\x18\x03 \x01(\v2\x0e.zchat.v1.ChatH\x00R\vchatUpdated\x123\n" +
	"\n" +
	"qr_updated\x18\x04 \x01(\v2\x12.zchat.v1.QRUpdateH\x00R\tqrUpdated\x12F\n" +
	"\x10connection_state\x18\x05 \x01(\v2\x19.zchat.v1.ConnectionStateH\x00R\x0fconnectionState\x12C\n" +
	"\x0fmessage_deleted\x18\x06 \x01(\v2\x18.zchat.v1.MessageDeletedH\x00R\x0emessageDeletedB\t\n" +
	"\apayload*\xb6\x01\n" +
	"\rMessageStatus\x12\x1e\n" +
	"\x1aMESSAGE_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16MESSAGE_STATUS_PENDING\x10\x01\x12\x17\n" +
	"\x13MESSAGE_STATUS_SENT\x10\x02\x12\x1c\n" +
	"\x18MESSAGE_STATUS_DELIVERED\x10\x03\x12\x17\n" +
	"\x13MESSAGE_STATUS_READ\x10\x04\x12\x19\n" +
	"\x15MESSAGE_STATUS_FAILED\x10\x05*\xbe\x01\n" +
	"\x10ConnectionStatus\x12!\n" +
	"\x1dCONNECTION_STATUS_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1eCONNECTION_STATUS_DISCONNECTED\x10\x01\x12 \n" +
	"\x1cCONNECTION_STATUS_CONNECTING\x10\x02\x12\x1f\n" +
	"\x1bCONNECTION_STATUS_CONNECTED\x10\x03\x12 \n" +
	"\x1cCONNECTION_STATUS_LOGGED_OUT\x10\x042\x91\a\n" +
	"\vChatService\x12A\n" +
	"\bGetChats\x12\x19.zchat.v1.GetChatsRequest\x1a\x1a.zchat.v1.GetChatsResponse\x12J\n" +
	"\vGetMessages\x12\x1c.zchat.v1.GetMessagesRequest\x1a\x1d.zchat.v1.GetMessagesResponse\x12J\n" +
	"\vSendMessage\x12\x1c.zchat.v1.SendMessageRequest\x1a\x1d.zchat.v1.SendMessageResponse\x12D\n" +
	"\tSendMedia\x12\x1a.zchat.v1.SendMediaRequest\x1a\x1b.zchat.v1.SendMediaResponse\x12S\n" +
	"\x0eForwardMessage\x12\x1f.zchat.v1.ForwardMessageRequest\x1a .zchat.v1.ForwardMessageResponse\x12P\n" +
	"\rDeleteMessage\x12\x1e.zchat.v1.DeleteMessageRequest\x1a\x1f.zchat.v1.DeleteMessageResponse\x12G\n" +
	"\n" +
	"UpdateChat\x12\x1b.zchat.v1.UpdateChatRequest\x1a\x1c.zchat.v1.UpdateChatResponse\x12T\n" +
	"\x12GetConnectionState\x12#.zchat.v1.GetConnectionStateRequest\x1a\x19.zchat.v1.ConnectionState\x12;\n" +
	"\x06Logout\x12\x17.zchat.v1.LogoutRequest\x1a\x18.zchat.v1.LogoutResponse\x12P\n" +
	"\rDownloadMedia\x12\x1e.zchat.v1.DownloadMediaRequest\x1a\x1f.zchat.v1.DownloadMediaResponse\x12J\n" +
	"\vSearchChats\x12\x1c.zchat.v1.SearchChatsRequest\x1a\x1d.zchat.v1.SearchChatsResponse\x12@\n" +
	"\fStreamEvents\x12\x1d.zchat.v1.StreamEventsRequest\x1a\x0f.zchat.v1.Event0\x01B7Z5github.com/zealish/zchat/packages/ipc/zchatv1;zchatv1b\x06proto3"

var (
	file_zchat_v1_zchat_proto_rawDescOnce sync.Once
	file_zchat_v1_zchat_proto_rawDescData []byte
)

func file_zchat_v1_zchat_proto_rawDescGZIP() []byte {
	file_zchat_v1_zchat_proto_rawDescOnce.Do(func() {
		file_zchat_v1_zchat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_zchat_v1_zchat_proto_rawDesc), len(file_zchat_v1_zchat_proto_rawDesc)))
	})
	return file_zchat_v1_zchat_proto_rawDescData
}

var file_zchat_v1_zchat_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_zchat_v1_zchat_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_zchat_v1_zchat_proto_goTypes = []any{
	(MessageStatus)(0),                // 0: zchat.v1.MessageStatus
	(ConnectionStatus)(0),             // 1: zchat.v1.ConnectionStatus
	(*Chat)(nil),                      // 2: zchat.v1.Chat
	(*Message)(nil),                   // 3: zchat.v1.Message
	(*QuotedMessage)(nil),             // 4: zchat.v1.QuotedMessage
	(*MediaInfo)(nil),                 // 5: zchat.v1.MediaInfo
	(*ConnectionState)(nil),           // 6: zchat.v1.ConnectionState
	(*GetChatsRequest)(nil),           // 7: zchat.v1.GetChatsRequest
	(*GetChatsResponse)(nil),          // 8: zchat.v1.GetChatsResponse
	(*GetMessagesRequest)(nil),        // 9: zchat.v1.GetMessagesRequest
	(*GetMessagesResponse)(nil),       // 10: zchat.v1.GetMessagesResponse
	(*SendMessageRequest)(nil),        // 11: zchat.v1.SendMessageRequest
	(*SendMessageResponse)(nil),       // 12: zchat.v1.SendMessageResponse
	(*SendMediaRequest)(nil),          // 13: zchat.v1.SendMediaRequest
	(*SendMediaResponse)(nil),         // 14: zchat.v1.SendMediaResponse
	(*ForwardMessageRequest)(nil),     // 15: zchat.v1.ForwardMessageRequest
	(*ForwardMessageResponse)(nil),    // 16: zchat.v1.ForwardMessageResponse
	(*DeleteMessageRequest)(nil),      // 17: zchat.v1.DeleteMessageRequest
	(*DeleteMessageResponse)(nil),     // 18: zchat.v1.DeleteMessageResponse
	(*UpdateChatRequest)(nil),         // 19: zchat.v1.UpdateChatRequest
	(*UpdateChatResponse)(nil),        // 20: zchat.v1.UpdateChatResponse
	(*GetConnectionStateRequest)(nil), // 21: zchat.v1.GetConnectionStateRequest
	(*LogoutRequest)(nil),             // 22: zchat.v1.LogoutRequest
	(*LogoutResponse)(nil),            // 23: zchat.v1.LogoutResponse
	(*DownloadMediaRequest)(nil),      // 24: zchat.v1.DownloadMediaRequest
	(*DownloadMediaResponse)(nil),     // 25: zchat.v1.DownloadMediaResponse
	(*SearchChatsRequest)(nil),        // 26: zchat.v1.SearchChatsRequest
	(*SearchChatsResponse)(nil),       // 27: zchat.v1.SearchChatsResponse
	(*StreamEventsRequest)(nil),       // 28: zchat.v1.StreamEventsRequest
	(*QRUpdate)(nil),                  // 29: zchat.v1.QRUpdate
	(*MessageDeleted)(nil),            // 30: zchat.v1.MessageDeleted
	(*Event)(nil),                     // 31: zchat.v1.Event
}
var file_zchat_v1_zchat_proto_depIdxs = []int32{
	0,  // 0: zchat.v1.Message.status:type_name -> zchat.v1.MessageStatus
	5,  // 1: zchat.v1.Message.media:type_name -> zchat.v1.MediaInfo
	4,  // 2: zchat.v1.Message.quoted:type_name -> zchat.v1.QuotedMessage
	1,  // 3: zchat.v1.ConnectionState.status:type_name -> zchat.v1.ConnectionStatus
	2,  // 4: zchat.v1.GetChatsResponse.chats:type_name -> zchat.v1.Chat
	3,  // 5: zchat.v1.GetMessagesResponse.messages:type_name -> zchat.v1.Message
	3,  // 6: zchat.v1.SendMessageResponse.message:type_name -> zchat.v1.Message
	3,  // 7: zchat.v1.SendMediaResponse.message:type_name -> zchat.v1.Message
	3,  // 8: zchat.v1.ForwardMessageResponse.message:type_name -> zchat.v1.Message
	2,  // 9: zchat.v1.UpdateChatResponse.chat:type_name -> zchat.v1.Chat
	3,  // 10: zchat.v1.DownloadMediaResponse.message:type_name -> zchat.v1.Message
	2,  // 11: zchat.v1.SearchChatsResponse.chats:type_name -> zchat.v1.Chat
	3,  // 12: zchat.v1.Event.message_received:type_name -> zchat.v1.Message
	3,  // 13: zchat.v1.Event.message_updated:type_name -> zchat.v1.Message
	2,  // 14: zchat.v1.Event.chat_updated:type_name -> zchat.v1.Chat
	29, // 15: zchat.v1.Event.qr_updated:type_name -> zchat.v1.QRUpdate
	6,  // 16: zchat.v1.Event.connection_state:type_name -> zchat.v1.ConnectionState
	30, // 17: zchat.v1.Event.message_deleted:type_name -> zchat.v1.MessageDeleted
	7,  // 18: zchat.v1.ChatService.GetChats:input_type -> zchat.v1.GetChatsRequest
	9,  // 19: zchat.v1.ChatService.GetMessages:input_type -> zchat.v1.GetMessagesRequest
	11, // 20: zchat.v1.ChatService.SendMessage:input_type -> zchat.v1.SendMessageRequest
	13, // 21: zchat.v1.ChatService.SendMedia:input_type -> zchat.v1.SendMediaRequest
	15, // 22: zchat.v1.ChatService.ForwardMessage:input_type -> zchat.v1.ForwardMessageRequest
	17, // 23: zchat.v1.ChatService.DeleteMessage:input_type -> zchat.v1.DeleteMessageRequest
	19, // 24: zchat.v1.ChatService.UpdateChat:input_type -> zchat.v1.UpdateChatRequest
	21, // 25: zchat.v1.ChatService.GetConnectionState:input_type -> zchat.v1.GetConnectionStateRequest
	22, // 26: zchat.v1.ChatService.Logout:input_type -> zchat.v1.LogoutRequest
	24, // 27: zchat.v1.ChatService.DownloadMedia:input_type -> zchat.v1.DownloadMediaRequest
	26, // 28: zchat.v1.ChatService.SearchChats:input_type -> zchat.v1.SearchChatsRequest
	28, // 29: zchat.v1.ChatService.StreamEvents:input_type -> zchat.v1.StreamEventsRequest
	8,  // 30: zchat.v1.ChatService.GetChats:output_type -> zchat.v1.GetChatsResponse
	10, // 31: zchat.v1.ChatService.GetMessages:output_type -> zchat.v1.GetMessagesResponse
	12, // 32: zchat.v1.ChatService.SendMessage:output_type -> zchat.v1.SendMessageResponse
	14, // 33: zchat.v1.ChatService.SendMedia:output_type -> zchat.v1.SendMediaResponse
	16, // 34: zchat.v1.ChatService.ForwardMessage:output_type -> zchat.v1.ForwardMessageResponse
	18, // 35: zchat.v1.ChatService.DeleteMessage:output_type -> zchat.v1.DeleteMessageResponse
	20, // 36: zchat.v1.ChatService.UpdateChat:output_type -> zchat.v1.UpdateChatResponse
	6,  // 37: zchat.v1.ChatService.GetConnectionState:output_type -> zchat.v1.ConnectionState
	23, // 38: zchat.v1.ChatService.Logout:output_type -> zchat.v1.LogoutResponse
	25, // 39: zchat.v1.ChatService.DownloadMedia:output_type -> zchat.v1.DownloadMediaResponse
	27, // 40: zchat.v1.ChatService.SearchChats:output_type -> zchat.v1.SearchChatsResponse
	31, // 41: zchat.v1.ChatService.StreamEvents:output_type -> zchat.v1.Event
	30, // [30:42] is the sub-list for method output_type
	18, // [18:30] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_zchat_v1_zchat_proto_init() }
func file_zchat_v1_zchat_proto_init() {
	if File_zchat_v1_zchat_proto != nil {
		return
	}
	file_zchat_v1_zchat_proto_msgTypes[17].OneofWrappers = []any{}
	file_zchat_v1_zchat_proto_msgTypes[29].OneofWrappers = []any{
		(*Event_MessageReceived)(nil),
		(*Event_MessageUpdated)(nil),
		(*Event_ChatUpdated)(nil),
		(*Event_QrUpdated)(nil),
		(*Event_ConnectionState)(nil),
		(*Event_MessageDeleted)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_zchat_v1_zchat_proto_rawDesc), len(file_zchat_v1_zchat_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_zchat_v1_zchat_proto_goTypes,
		DependencyIndexes: file_zchat_v1_zchat_proto_depIdxs,
		EnumInfos:         file_zchat_v1_zchat_proto_enumTypes,
		MessageInfos:      file_zchat_v1_zchat_proto_msgTypes,
	}.Build()
	File_zchat_v1_zchat_proto = out.File
	file_zchat_v1_zchat_proto_goTypes = nil
	file_zchat_v1_zchat_proto_depIdxs = nil
}
